package enums;

public enum Operations {
    LOGIN_CANDIDATE,
    LOGOUT_CANDIDATE,
    SIGNUP_CANDIDATE,
    LOOKUP_ACCOUNT_CANDIDATE,
    UPDATE_ACCOUNT_CANDIDATE,
    DELETE_ACCOUNT_CANDIDATE,
    LOGIN_RECRUITER,
    LOGOUT_RECRUITER,
    SIGNUP_RECRUITER,
    LOOKUP_ACCOUNT_RECRUITER,
    UPDATE_ACCOUNT_RECRUITER,
    DELETE_ACCOUNT_RECRUITER,
    INCLUDE_SKILL,
    LOOKUP_SKILL,
    LOOKUP_SKILLSET,
    DELETE_SKILL,
    UPDATE_SKILL,
    INCLUDE_JOB,
    LOOKUP_JOBSET,
    LOOKUP_JOB,
    DELETE_JOB,
    UPDATE_JOB,
    SEARCH_JOB,
    FORCED_QUIT
}
