package enums;

public enum Statuses {
    SUCCESS,
    INVALID_LOGIN,
    USER_NOT_FOUND,
    USER_EXISTS,
    INVALID_PASSWORD,
    INVALID_EMAIL,
    INVALID_FIELD,
    INVALID_OPERATION,
    INVALID_TOKEN,
    SKILL_NOT_EXIST,
    SKILL_EXISTS,
    JOB_NOT_FOUND,
    ERROR,

    SERVER_DOWN
}
